#!/bin/bash

echo -n "Enter branch name: "
read BRANCH
echo -n "Enter Github username: "
read USERNAME
echo -n "Enter Github repo name: "
read REPO

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

if [ "$(find .)" == "." ]; then
    echo "# $REPO" >> README.md
fi

git init
git add .
git commit -m "Init commit"
git branch -M "$BRANCH"
git remote add origin "https://github.com/$USERNAME/$REPO.git"
git push -u origin "$BRANCH"
